# Dependencies #################################################################
markdown:         kramdown
highlighter:      rouge

# Permalinks ###################################################################
permalink:        "pretty"

# Setup ########################################################################
title:            "Blog do Lucão"
tagline:          "Bugador!"
description:      "Bugador!"
url:              "https://lucrib.github.io/blog"
baseurl:          ""
encoding:         "utf-8"
timezone:         "America/Sao_Paulo"

paginate:         5

# Custom vars ##################################################################
version:          00.01.00-ALPHA_1

# Social media #################################################################
github:
  repo:           "https://github.com/lucrib"

linkedin:
  link:           "https://br.linkedin.com/in/lucasribeirotester/en/"

author:
  name:           "Lucas Ribeiro"
  url:            "https://twitter.com/lucao_ribeiro"
#Gems ##########################################################################
gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
  - pygments.rb

paginate_path: "page:num"

# Own Headers ##################################################################
webrick:
    headers:
      selenium-ready: true
