# Site settings
email: "lucasribeiro1990@gmail.com"
baseurl: "/blog"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-85624987-1"

# SEO settings
title: "LucRib"
description: "Bem vindo ao blog de LucRib"
url: "https://lucrib.github.io/blog"
twitter_username: "lucrib_"
default_img: "https://pbs.twimg.com/profile_images/854529093404155905/jlITFltG_400x400.jpg"

# Profile settings
name: "LucRib"
profile_img: "https://pbs.twimg.com/profile_images/854529093404155905/jlITFltG_400x400.jpg"
profile: "Lucas Ribeiro - Estou há mais de 5 anos na área de testes e atualmente
 sou Desenvolvedor de Aplicações Embarcadas no FIT-Instituto de Tecnologia.
Atualmente programo mais em C/C++, porém já fiz muita automação de testes com
 python e java e continuo antenado nos fóruns de testes, especialmente sobre automação."
social:
  github: "https://github.com/lucrib/blog/"
  linkedin: "https://linkedin.com/lucrib"
  twitter: "https://twitter.com/lucrib_"
  facebook: "https://facebook.com/lucrib"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md", "vendor"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
