# Site settings
email: "lucasribeiro1990@gmail.com"
baseurl: "/trophy-jekyll"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: "LucRib"
description: "Bem vindo ao blog de LucRib"
url: "https://lucrib.github.io/trophy-jekyll"
twitter_username: "lucrib_"
default_img: "/assets/images/bugs.jpg"

# Profile settings
name: "LucRib"
profile_img: "https://pbs.twimg.com/profile_images/854529093404155905/jlITFltG_400x400.jpg"
profile: "This is a brief explanations of your profile that will appear in all the posts pages."
social:
  github: "https://github.com/lucrib/trophy-jekyll"
  linkedin: "https://linkedin.com/lucrib"
  twitter: "https://twitter.com/lucrib_"
  facebook: "https://facebook.com/lucrib"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md", "vendor"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
