# Site settings
email: "lucasribeiro1990@gmail.com"
baseurl: "/blog"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-85624987-1"

# SEO settings
title: "LucRib"
description:
  "Blog pessoal de Lucas Ribeiro com posts sobre desenvolvimento de software, tecnologia, intermcâmbio,
  a vida o universo e tudos mais..."
url: "https://lucrib.github.io/blog"
twitter_username: "lucrib_"
default_img: "https://lucrib.github.io/blog/assets/img/profile.jpg"

# Profile settings
name: "LucRib"
profile_img: "/blog/assets/img/profile.jpg"
profile: "Lucas Ribeiro - Desenvolvedor de software com foco em testes automatizados."
social:
  github: "https://github.com/lucrib"
  linkedin: "https://linkedin.com/lucrib"
  twitter: "https://twitter.com/lucrib_"
  facebook: "https://facebook.com/lucrib"

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md", "vendor"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
